### ISSUE TITLE
Exception "Unexpected variantName: '$Codex_Ent_Ground_Struct_Name;'" at 2/8/2024 11:39:52 AM -06:00

### ISSUE THREAD

**Issue by Viral3651** [njthomson/SrvSurvey#60] opened 2024-02-08 17:40 UTC
### What happened?

Scanning and harvesting Tellurium crystal shards at HIP 36601 when it suddenly stopped keeping track of my scans and locations. Nothing updated after that.

### Version

1.1.0.37

### Exception message

Unexpected variantName: '$Codex_Ent_Ground_Struct_Name;'

### Exception stack

   at SrvSurvey.canonn.CodexRef.matchFromVariant(String variantName)
   at SrvSurvey.game.SystemData.onJournalEntry(ScanOrganic entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.SystemData.Journals_onJournalEntry(JournalEntry entry)
   at SrvSurvey.game.Game.initSystemData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<Main_Load>b__10_7()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at SrvSurvey.Main.<Main_Load>b__10_2()

### Relevant log output

```shell
{"part":1,"Odyssey":true,"gameversion":"4.0.0.1701","build":"r299332/r0 ","timestamp":"2024-02-08T15:24:28Z","event":"Fileheader"}
11:38:48: Game.initSystemData: playForwards 'Scan' (2/8/2024 4:56:47 PM)
11:38:48: Game.initSystemData: playForwards 'Scan' (2/8/2024 4:56:49 PM)
11:38:48: Game.initSystemData: playForwards 'Scan' (2/8/2024 4:56:51 PM)
11:38:48: Game.initSystemData: playForwards 'FSSBodySignals' (2/8/2024 4:56:54 PM)
11:38:48: Game.initSystemData: playForwards 'Scan' (2/8/2024 4:56:55 PM)
11:38:48: Game.initSystemData: playForwards 'FSSBodySignals' (2/8/2024 4:56:56 PM)
11:38:48: Game.initSystemData: playForwards 'Scan' (2/8/2024 4:56:56 PM)
11:38:48: Game.initSystemData: playForwards 'Scan' (2/8/2024 4:56:59 PM)
11:38:48: Game.initSystemData: playForwards 'Scan' (2/8/2024 4:57:02 PM)
11:38:48: Game.initSystemData: playForwards 'FSSAllBodiesFound' (2/8/2024 4:57:02 PM)
11:38:48: Game.initSystemData: playForwards 'SAAScanComplete' (2/8/2024 5:10:03 PM)
11:38:48: Game.initSystemData: playForwards 'SAASignalsFound' (2/8/2024 5:10:03 PM)
11:38:48: Game.initSystemData: playForwards 'Scan' (2/8/2024 5:10:04 PM)
11:38:48: Game.initSystemData: playForwards 'ApproachBody' (2/8/2024 5:11:13 PM)
11:38:48: Game.initSystemData: playForwards 'Touchdown' (2/8/2024 5:12:56 PM)
11:38:48: Game.initSystemData: playForwards 'Disembark' (2/8/2024 5:13:44 PM)
11:38:48: Game.initSystemData: playForwards 'CodexEntry' (2/8/2024 5:13:59 PM)
11:38:48: Game.initSystemData: playForwards 'ScanOrganic' (2/8/2024 5:13:59 PM)
11:38:48: System.Exception: Unexpected variantName: '$Codex_Ent_Ground_Struct_Name;'
   at SrvSurvey.canonn.CodexRef.matchFromVariant(String variantName)
   at SrvSurvey.game.SystemData.onJournalEntry(ScanOrganic entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.SystemData.Journals_onJournalEntry(JournalEntry entry)
   at SrvSurvey.game.Game.initSystemData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<Main_Load>b__10_7()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at SrvSurvey.Main.<Main_Load>b__10_2()
11:38:48: isFirewallProblem?
System.Exception: Unexpected variantName: '$Codex_Ent_Ground_Struct_Name;'
   at SrvSurvey.canonn.CodexRef.matchFromVariant(String variantName)
   at SrvSurvey.game.SystemData.onJournalEntry(ScanOrganic entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.game.SystemData.Journals_onJournalEntry(JournalEntry entry)
   at SrvSurvey.game.Game.initSystemData()
   at SrvSurvey.game.Game.initializeFromJournal(LoadGame loadEntry)
   at SrvSurvey.game.Game..ctor(String cmdr)
   at SrvSurvey.Main.newGame()
   at SrvSurvey.Main.<Main_Load>b__10_7()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at SrvSurvey.Main.<Main_Load>b__10_2()
```

**Comment by GaryMac1971** [comment] 2024-02-11 10:25
Also getting the same issue with a system/planet with Crystal Shards. Will attempt another planet to see if this crashes.

**Comment by GaryMac1971** [comment] 2024-02-11 10:33
Confirmed, only on planets with Crystal Shards.

**Comment by njthomson** [comment] 2024-02-22 04:25
This has since been fixed in more recent builds. Try the latest from https://github.com/njthomson/SrvSurvey/releases

**Comment by njthomson** [comment] 2024-02-27 22:52
@GaryMac1971 or @Viral3651 - let me know if you see this still in recent builds:
https://github.com/njthomson/SrvSurvey/releases/tag/1.1.0.50

**Closed by njthomson** 2024-02-27 22:52 UTC
Labels: bug

**Comment by GaryMac1971** [comment] 2024-02-28 10:11
Will let you know. Thanks @njthomson!

Gary
