### ISSUE TITLE
NullReferenceException "Object reference not set to an instance of an object." at 10/24/2024 1:46:58 AM -04:00

### ISSUE THREAD

**Issue by OPlurker1005** [njthomson/SrvSurvey#135] opened 2024-10-24 05:49 UTC
### What happened?

I jumped to what I thought was going to be a nutron star, the jump took longer then normal and then the game crashed. When I logged back in I was at a white dworf.

### Version

2.0.2.17

### Exception message

Object reference not set to an instance of an object.

### Exception stack

   at SrvSurvey.PlotFSSInfo.onJournalEntry(Scan entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.PlotBase.Journals_onJournalEntry(JournalEntry entry, Int32 index)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at SrvSurvey.JournalWatcher.readEntry()
   at SrvSurvey.JournalFile.readEntries(String targetCmdr)
   at SrvSurvey.Program.crashGuard(Boolean beginInvoke, Action func)

### Relevant log output

```shell
00:57:24: Mode change ExternalPanel => SuperCruising
00:57:24: Program.Creating plotter: PlotJumpInfo
00:57:24: Program.Showing plotter: PlotJumpInfo
00:57:44: Program.Closing plotter: PlotJumpInfo
00:58:12: PlotSysStatus.OnPaintBackground error: System.ArgumentException: Parameter is not valid.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at SrvSurvey.PlotBase.OnPaintBackground(PaintEventArgs e)
01:19:28: Mode change SuperCruising => ExternalPanel
01:19:31: Mode change ExternalPanel => SuperCruising
01:19:40: Mode change SuperCruising => Offline
01:19:40: Program.Closing plotter: PlotSysStatus
01:19:40: crashGuard System.NullReferenceException: Object reference not set to an instance of an object.
   at SrvSurvey.PlotFSSInfo.onJournalEntry(Scan entry)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at SrvSurvey.PlotBase.Journals_onJournalEntry(JournalEntry entry, Int32 index)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
--- End of stack trace from previous location ---
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at SrvSurvey.JournalWatcher.readEntry()
   at SrvSurvey.JournalFile.readEntries(String targetCmdr)
   at SrvSurvey.Program.crashGuard(Boolean beginInvoke, Action func)
01:19:44: EliteDangerous process died?!
01:19:44: Main.removeGame, has old game: True
01:19:44: Program.CloseAllPlotters
01:19:44: Program.Closing plotter: PlotPulse
01:31:56: EliteDangerous window reposition: {X=0,Y=0,Width=1920,Height=1080} => {X=0,Y=0,Width=0,Height=0}
01:31:56: Program.repositionPlotters: 0, rect{X=0,Y=0,Width=0,Height=0}
01:41:50: Opening link: (length: 29)
https://discord.gg/QZsMu2SkSA

01:42:17: Opening link: (length: 4488)
https://github.com:443/njthomson/SrvSurvey/issues/new?template=crash-report.yml&title=NullReferenceException+%22Object+reference+not+set+to+an+instance+of+an+object.%22+at+10%2F24%2F2024+1%3A42%3A17+A

01:42:53: Opening link: (length: 29)
https://discord.gg/QZsMu2SkSA

01:45:01: Opening link: (length: 45)
https://github.com/njthomson/SrvSurvey/issues
```

**Comment by njthomson** [comment] 2024-10-24 18:22
Thank you @OPlurker1005 for reporting this - let me take a look at this.

**Comment by njthomson** [comment] 2024-10-24 18:23
The game crashing is the root cause, I have code that cleans up in those cases but something asynchronous was not expecting that clean-up.

**Comment by njthomson** [comment] 2024-10-24 19:48
This should be fixed as with this build. Give me a shout if you see anything again.

https://github.com/njthomson/SrvSurvey/releases/tag/2.0.2.19

**Closed by njthomson** 2024-10-24 19:48 UTC
Labels: bug
